version: '3'

services:

  app:
    build: 
      context: node
    container_name: app
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root 

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    build: 
      context: nginx
    container_name: nginx
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  mysql:
    driver: local
  